name = "HerbCore"
uuid = "2b23ba43-8213-43cb-b5ea-38c12b45bd45"
version = "1.1.0"
authors = ["Jaap de Jong <jaapdejong15@gmail.com>", "Nicolae Filat <N.Filat@student.tudelft.nl>", "Tilman Hinnerichs <t.r.hinnerichs@tudelft.nl>", "Sebastijan Dumancic <s.dumancic@tudelft.nl>"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DispatchDoctor = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[compat]
AbstractTrees = "0.4.5"
DispatchDoctor = "0.4.28"
MacroTools = "0.5.15"
StaticArrays = "1.9.18"
StyledStrings = "1"
julia = "1.10"
